// <auto-generated />
using CustomWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomWebApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200408165946_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomWebApi.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Name = "Hiking"
                        },
                        new
                        {
                            ActivityId = 2,
                            Name = "Running"
                        },
                        new
                        {
                            ActivityId = 3,
                            Name = "Camping"
                        },
                        new
                        {
                            ActivityId = 4,
                            Name = "Traveling"
                        },
                        new
                        {
                            ActivityId = 5,
                            Name = "Gardening"
                        },
                        new
                        {
                            ActivityId = 6,
                            Name = "Fishing"
                        },
                        new
                        {
                            ActivityId = 7,
                            Name = "Hunting"
                        },
                        new
                        {
                            ActivityId = 8,
                            Name = "Exercising"
                        },
                        new
                        {
                            ActivityId = 9,
                            Name = "Bicycling"
                        },
                        new
                        {
                            ActivityId = 10,
                            Name = "Swimming"
                        },
                        new
                        {
                            ActivityId = 11,
                            Name = "Boating"
                        },
                        new
                        {
                            ActivityId = 12,
                            Name = "Skiing"
                        },
                        new
                        {
                            ActivityId = 13,
                            Name = "Bowling"
                        },
                        new
                        {
                            ActivityId = 14,
                            Name = "Reading"
                        },
                        new
                        {
                            ActivityId = 15,
                            Name = "Kayaking"
                        },
                        new
                        {
                            ActivityId = 16,
                            Name = "Cooking"
                        },
                        new
                        {
                            ActivityId = 17,
                            Name = "Painting"
                        },
                        new
                        {
                            ActivityId = 18,
                            Name = "Gaming"
                        },
                        new
                        {
                            ActivityId = 19,
                            Name = "Crafting"
                        },
                        new
                        {
                            ActivityId = 20,
                            Name = "Collecting"
                        });
                });

            modelBuilder.Entity("CustomWebApi.Models.Fandom", b =>
                {
                    b.Property<int>("FandomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FandomId");

                    b.ToTable("Fandoms");

                    b.HasData(
                        new
                        {
                            FandomId = 1,
                            Name = "The Lord of the Rings"
                        },
                        new
                        {
                            FandomId = 2,
                            Name = "Harry Potter"
                        },
                        new
                        {
                            FandomId = 3,
                            Name = "Star Wars"
                        },
                        new
                        {
                            FandomId = 4,
                            Name = "Game of Thrones"
                        },
                        new
                        {
                            FandomId = 5,
                            Name = "Marvel"
                        },
                        new
                        {
                            FandomId = 6,
                            Name = "Stranger Things"
                        },
                        new
                        {
                            FandomId = 7,
                            Name = "The DC Universe"
                        },
                        new
                        {
                            FandomId = 8,
                            Name = "Pokemon"
                        },
                        new
                        {
                            FandomId = 9,
                            Name = "Star Trek"
                        },
                        new
                        {
                            FandomId = 10,
                            Name = "The Walking Dead"
                        },
                        new
                        {
                            FandomId = 11,
                            Name = "Fortnite"
                        },
                        new
                        {
                            FandomId = 12,
                            Name = "Minecraft"
                        });
                });

            modelBuilder.Entity("CustomWebApi.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Name = "The Departed"
                        },
                        new
                        {
                            MovieId = 2,
                            Name = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 3,
                            Name = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 4,
                            Name = "The Lion King"
                        },
                        new
                        {
                            MovieId = 5,
                            Name = "Titanic"
                        },
                        new
                        {
                            MovieId = 6,
                            Name = "The Big Lebowski"
                        },
                        new
                        {
                            MovieId = 7,
                            Name = "Before Sunrise"
                        },
                        new
                        {
                            MovieId = 8,
                            Name = "Jurassic Park"
                        },
                        new
                        {
                            MovieId = 9,
                            Name = "Toy Story 2"
                        },
                        new
                        {
                            MovieId = 10,
                            Name = "Thelma and Louise"
                        });
                });

            modelBuilder.Entity("CustomWebApi.Models.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusicId");

                    b.ToTable("Music");

                    b.HasData(
                        new
                        {
                            MusicId = 1,
                            Name = "The Beatles"
                        },
                        new
                        {
                            MusicId = 2,
                            Name = "Guns N' Roses"
                        },
                        new
                        {
                            MusicId = 3,
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            MusicId = 4,
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            MusicId = 5,
                            Name = "Queen"
                        },
                        new
                        {
                            MusicId = 6,
                            Name = "The Rolling Stones"
                        },
                        new
                        {
                            MusicId = 7,
                            Name = "Elvis Presley"
                        },
                        new
                        {
                            MusicId = 8,
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            MusicId = 9,
                            Name = "Elton John"
                        },
                        new
                        {
                            MusicId = 10,
                            Name = "Madonna"
                        },
                        new
                        {
                            MusicId = 11,
                            Name = "Rihanna"
                        },
                        new
                        {
                            MusicId = 12,
                            Name = "Eminem"
                        },
                        new
                        {
                            MusicId = 13,
                            Name = "Taylor Swift"
                        },
                        new
                        {
                            MusicId = 14,
                            Name = "Mariah Carey"
                        },
                        new
                        {
                            MusicId = 15,
                            Name = "Eagles"
                        });
                });

            modelBuilder.Entity("CustomWebApi.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            Name = "American Football"
                        },
                        new
                        {
                            SportId = 2,
                            Name = "Baseball"
                        },
                        new
                        {
                            SportId = 3,
                            Name = "Basketball"
                        },
                        new
                        {
                            SportId = 4,
                            Name = "Hockey"
                        },
                        new
                        {
                            SportId = 5,
                            Name = "Soccer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
